[workspace]
members = [
    "ss-str-fmt",
    "html-to-subscript",
    "ss-language-server",
    "ss-freeform-format",
    "subscript-compiler",
]

exclude = [
    "local-dev/ss-drawing-lab",
    "local-dev/cavalier_contours",
    "local-dev/cavalier_contours_ffi",
]

