[workspace]
members = [
    "ss-language-server",
    "ss-freeform-format",
    "subscript-ast",
    "subscript",
]

exclude = [
    "ss-drawing-lab",
    "cavalier_contours",
    "cavalier_contours_ffi",
]

