[package]
name = "subscript"
version = "0.4.0"
authors = ["Colbyn Wadman <hello@colbyn.com>"]
edition = "2018"
repository = "https://github.com/subscript-publishing"
homepage = "https://github.com/subscript-publishing"
license = "MPL-2.0"
description = "reserved 👉 for the new compiler (and other infrastructure) see https://github.com/subscript-publishing 👉 We decided to move away from the old monolithic codebase and split everything into smaller sub-projects (for now)."
keywords = ['site', 'static', 'generator', 'latex', 'tex']
categories = [
    'mathematics',
    'science',
]

[dependencies]
