[package]
name = "ss_freeform_format"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1"
itertools = "0.10.0"
either = "1.8.0"
rmp-serde = "1.1.0"
plist = "1.3.1"
svg2pdf = "0.4.0"
